id: PD7DCD674
initial_creation_type: input
source_metadata:
  title: Marpa Lotsāwa Series
  language: en
  description: 'Texts by and about the great Marpa Chökyi Lodrö (mar pa chos kyi blo
    gros, c.1012–1097), renowned as the founder of the Marpa Kagyü tradition and teacher
    of Milarepa:'
  volume:
    080082508dd546d898bd5c051d12cc58:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Guru Yoga
    6f61e1cfb837436b93412f9d2f0ad59f:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Guru Yoga
    54af649218d34c42b8bf2280ba2296b9:
      title: Guru Yoga of Lord Marpa Lotsāwa
      parent: Guru Yoga
    8d9fd2c910d04a42b6a06a5d07d3b2e9:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Guru Yoga
    509cca8a95c9498e8e4ee30748a4d697:
      title: Prayer to Lord Marpa, Consort and Heirs
      parent: Prayers
    7ca050efabcc48d09aa617f7a33cf039:
      title: 'Song of Devotion: A Prayer to Lord Marpa Lotsāwa'
      parent: Prayers
    ad8350d1568d464db6866fe6380a2991:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
created_at: '2022-03-01T00:43:52.483465'
last_modified_at: '2022-03-01T00:43:52.483472'
